# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bibliotheque' do
  # Comment the next line if you don't want to use dynamic frameworks

  pod 'SPAlert'
  use_frameworks!

  # Pods for Bibliotheque

end
